# Generated by Django 5.1.2 on 2024-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_special_occasion_alter_reservation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
