# Generated by Django 5.1.2 on 2024-11-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
