# Generated by Django 5.1.2 on 2024-11-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='special_occasion',
        ),
    ]
