# Generated by Django 5.1.2 on 2025-02-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_reservation_code_alter_reservation_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='code',
        ),
    ]
