# Generated by Django 5.1.2 on 2025-03-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_reservation_code_alter_reservation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$IHRA4Ha0vQpdcE2xn0PfTA$fWWtCLoC9BqWxGJsErsx31Rl8mCBGoTMIpaCKz8IsFI=', max_length=128),
        ),
    ]
