# Generated by Django 5.1.2 on 2025-03-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_reservation_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
