# Generated by Django 5.1.2 on 2025-02-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_reservation_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
